# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{speak_your_mind}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["fujimura"]
  s.date = %q{2010-01-11}
  s.description = %q{Shoulda(or plain Test::Unit) speaks to you more friendly in terminal}
  s.email = %q{ffujimurah@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/speak_your_mind.rb",
     "speak_your_mind.gemspec",
     "test/helper.rb",
     "test/test_speak_your_mind.rb"
  ]
  s.homepage = %q{http://github.com/fujimura/speak_your_mind}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{shoulda(and test/unit) with rspec-ish friendly output}
  s.test_files = [
    "test/test_speak_your_mind.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<redgreen>, [">= 0"])
    else
      s.add_dependency(%q<redgreen>, [">= 0"])
    end
  else
    s.add_dependency(%q<redgreen>, [">= 0"])
  end
end

